language: python
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
addons:
  apt:
    packages:
      - pandoc
install:
- pip install .
script:
- python -m unittest discover -s tests
before_deploy:
- pandoc --to rst -o README.rst README.md
deploy:
  provider: pypi
  user: iamlikeme
  password:
    secure: IuhH3NEYbYlV+AZKg2ytHAJSOWIUQZ1brpTjzIVYdhOiQ/uF+cp9LZIV8O7EpBBWABqSecKw937qLIkIyuxU5sP6J3kk538Q1GK2cbnwfy+DyMxlNrH0Yz7N9P7ouQXpdL8Za1yGH1vkPvq2p8u7qKW9IZb9rCNG7nX+snHlCPJhrv7EBwV5MImZPJuVF9E+WukPGg7DN5Ehvp7jb87CljIE3cwkiL18REVh0bMoQrSvnWqO19s0Wo++nrhha2IPT43Y+EWKb4AOK2acPJEKKhPDdobSF9lfmGOGWL8+A9QOCSvaryfPiHVx+vyfRuJ4yr2cGJrXJX4U7vD4m7CiEcADl0uPwJxNcrwWIqVgc3KqfoY7B5FoIyMUir4J1kuFYTtQj4zFzeXBPCVpT+psTMEOXoD1pNCH3HRVS9x3NY9gU2EACXBoffEvpcSK0WVgrcG/PmMNnG6fTrOJPg+ztHHSs1Yb5nW3dwpdR/6qabj11aIaLGRh7dBLqO8VYw+bztGXSIIX7dDP9ss4juUjDWzuMlbbEsk3eWayhInnbNBLpxh/ivCUxV1F1+kxW4v2Z2xyxIzxhP2CwnbtedVcQU1A43tTp2bjT5ui8mZdYMwJJlwrCUjxLJnllj7Y5aGNv5B5EcwY8wK+LWJz5PNkpiGgjgckAdmJMi57wTnWNe4=
  on:
    tags: true
