language: python
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+$/"
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install .[dev]
script:
- pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: diZjE896gqzWYxIE1xcxTfcQZJoEZ7DHVrGoexC7yj316XPA7fEMZjIvwthgfYG3w201lkLV+NmHEA+Rj9zy/ljJILtI5BelOETMnYfN81W1mCHJ/xiNEVBl0VU/ApEASWGLB0BBt505S9ROZGGb2Fcm6OY9zq3rOImdyRjjd5LOOZlDcnTgq1SWRx01n2Gbm2SC6Gda2EgDxD47D1/l94JVwWi7pNwBSiF3AUp5ycATAcMRTgjGeExOy3f/JxvI/6f3KdFXY5YLwY4yBtFRAkhJjH5iNkGTBG1J+RepyGYC4Yez8lMOITrEolB1ObpihOe0xK3TTNTpWFMOL43WhOdu+UpZyPht/s+GPOOnI+fGXG0cUsw3zBciagnXAlMtZih7SbXbprypAbxja747QoL5I1QyB7/sXKdXF+htk66MLX5IRpYJbSoS9MPvwfPK4DtTE5Z+Ixc5Sy1SjCakv3hY1okw/oywGi9kbP5l9ZXzkdeRNQ7SRyWDVhtcCJIO/3P8fz7ulQZdFsKUxXT8Pyb/KzOib3/sXnyqZlPvEYuINEw/nt2Z/ec6pffUD5PrugbQy8KDtMzVbqU2tX8Xkj0VXPFLw0Ouy5+oUyKWroYL6MQRsQ0qpze44IJuGaEBhPFjZSRxTES4E36x4XVjx8bEGL/Z36zMMt5Pq2kVF+A=
  on:
    tags: true
    python: '3.6'
